// Generated by Rampsonc, DO NOT EDIT
// source: schema.json
// namespace: JSchema

#pragma once

#include <string>
#include <vector>
#include <optional>
#include <cstdint>
#include <set>
#include <regex>
#include <cmath>
#include <sstream>
#include <stdexcept>
#include <variant>
#include <nlohmann/json.hpp>

namespace JSchema {

using json = nlohmann::json;

#ifndef RAMPSON_TYPES_DEFINED
#define RAMPSON_TYPES_DEFINED

struct ValidationError {
  std::string path;
  std::string message;
};

struct ValidationResult {
  std::vector<ValidationError> errors;

  bool valid() const { return errors.empty(); }

  void add(const std::string& path, const std::string& message) {
    errors.push_back({path, message});
  }

  void merge(const ValidationResult& other) {
    errors.insert(errors.end(), other.errors.begin(), other.errors.end());
  }

  std::string summary() const {
    if (errors.empty()) return "Validation passed.";
    std::ostringstream os;
    os << errors.size() << " validation error(s):\n";
    for (const auto& e : errors) {
      os << "  " << e.path << ": " << e.message << "\n";
    }
    return os.str();
  }
};

class JsonValue {
public:
  virtual ~JsonValue() = default;

  template <typename T>
  T* as() { return dynamic_cast<T*>(this); }

  template <typename T>
  const T* as() const { return dynamic_cast<const T*>(this); }

  template <typename T>
  bool is() const { return dynamic_cast<const T*>(this) != nullptr; }
};

#endif // RAMPSON_TYPES_DEFINED

struct TransformComponent;
struct GridPos;
struct Offset;
struct LayersItem;
struct SubSpritesItem;
struct SpriteComponent;
struct SeekPrimaryTargetTag;
struct HealthComponent;
struct ContactDamageComponent;
struct Shape;
struct ShapesItem;
struct BodyComponent;
struct Material;
struct TileComponent;
struct ArrowComponent;
struct AnchorPos;
struct OccupiedPositionsItem;
struct MultiTileComponent;
struct TurretComponent;
struct ComponentsItem;
struct Data;
struct Root;

struct TransformComponent : public JsonValue {
  struct Properties {
    struct Scale {
      static const char* name() { return "scale"; }
      static constexpr bool required = false;
    };
    struct Type {
      static const char* name() { return "type"; }
      static constexpr bool required = true;
      static const char* constValue() { return "TransformComponent"; }
    };
  };

  static ValidationResult validate(const json& j, const std::string& path = "") {
    ValidationResult result;
    if (!j.is_object()) { result.add(path, "Expected object"); return result; }
    if (!j.contains("type")) result.add(path.empty() ? "type" : path + ".type", "Required field missing");
    if (j.contains("scale")) {
      std::string fp = path.empty() ? "scale" : path + ".scale";
      if (!j["scale"].is_number()) {
        result.add(fp, "Expected number");
      } else {
        double val = j["scale"].get<double>();
      }
    }
    if (j.contains("type")) {
      std::string fp = path.empty() ? "type" : path + ".type";
      if (!j["type"].is_string()) {
        result.add(fp, "Expected string");
      } else {
        const auto& val = j["type"].get_ref<const std::string&>();
        if (val != "TransformComponent") result.add(fp, "Value does not match const");
      }
    }
    return result;
  }

  static TransformComponent fromJson(const json& j) {
    auto vr = validate(j);
    if (!vr.valid()) throw std::runtime_error(vr.summary());
    TransformComponent obj;
    if (j.contains("scale")) {
      obj.setScale(j["scale"].get<double>());
    }
    obj.setType(j.at("type").get<std::string>());
    return obj;
  }

  bool hasScale() const { return scale_.has_value(); }
  double getScale() const { return scale_.value(); }
  void setScale(double value) { scale_ = value; }

  const std::string& getType() const { return type_; }
  std::string& getType() { return type_; }
  void setType(const std::string& value) { type_ = value; }

private:
  std::optional<double> scale_;
  std::string type_;
};

struct GridPos : public JsonValue {
  struct Properties {
    struct X {
      static const char* name() { return "x"; }
      static constexpr bool required = true;
    };
    struct Y {
      static const char* name() { return "y"; }
      static constexpr bool required = true;
    };
  };

  static ValidationResult validate(const json& j, const std::string& path = "") {
    ValidationResult result;
    if (!j.is_object()) { result.add(path, "Expected object"); return result; }
    if (!j.contains("x")) result.add(path.empty() ? "x" : path + ".x", "Required field missing");
    if (!j.contains("y")) result.add(path.empty() ? "y" : path + ".y", "Required field missing");
    if (j.contains("x")) {
      std::string fp = path.empty() ? "x" : path + ".x";
      if (!j["x"].is_number()) {
        result.add(fp, "Expected number");
      } else {
        double val = j["x"].get<double>();
      }
    }
    if (j.contains("y")) {
      std::string fp = path.empty() ? "y" : path + ".y";
      if (!j["y"].is_number()) {
        result.add(fp, "Expected number");
      } else {
        double val = j["y"].get<double>();
      }
    }
    return result;
  }

  static GridPos fromJson(const json& j) {
    auto vr = validate(j);
    if (!vr.valid()) throw std::runtime_error(vr.summary());
    GridPos obj;
    obj.setX(j.at("x").get<double>());
    obj.setY(j.at("y").get<double>());
    return obj;
  }

  double getX() const { return x_; }
  void setX(double value) { x_ = value; }

  double getY() const { return y_; }
  void setY(double value) { y_ = value; }

private:
  double x_{};
  double y_{};
};

struct Offset : public JsonValue {
  struct Properties {
    struct X {
      static const char* name() { return "x"; }
      static constexpr bool required = true;
    };
    struct Y {
      static const char* name() { return "y"; }
      static constexpr bool required = true;
    };
  };

  static ValidationResult validate(const json& j, const std::string& path = "") {
    ValidationResult result;
    if (!j.is_object()) { result.add(path, "Expected object"); return result; }
    if (!j.contains("x")) result.add(path.empty() ? "x" : path + ".x", "Required field missing");
    if (!j.contains("y")) result.add(path.empty() ? "y" : path + ".y", "Required field missing");
    if (j.contains("x")) {
      std::string fp = path.empty() ? "x" : path + ".x";
      if (!j["x"].is_number()) {
        result.add(fp, "Expected number");
      } else {
        double val = j["x"].get<double>();
      }
    }
    if (j.contains("y")) {
      std::string fp = path.empty() ? "y" : path + ".y";
      if (!j["y"].is_number()) {
        result.add(fp, "Expected number");
      } else {
        double val = j["y"].get<double>();
      }
    }
    return result;
  }

  static Offset fromJson(const json& j) {
    auto vr = validate(j);
    if (!vr.valid()) throw std::runtime_error(vr.summary());
    Offset obj;
    obj.setX(j.at("x").get<double>());
    obj.setY(j.at("y").get<double>());
    return obj;
  }

  double getX() const { return x_; }
  void setX(double value) { x_ = value; }

  double getY() const { return y_; }
  void setY(double value) { y_ = value; }

private:
  double x_{};
  double y_{};
};

struct LayersItem : public JsonValue {
  struct Properties {
    struct Layer {
      static const char* name() { return "layer"; }
      static constexpr bool required = true;
    };
    struct Offset {
      static const char* name() { return "offset"; }
      static constexpr bool required = false;
    };
    struct Path {
      static const char* name() { return "path"; }
      static constexpr bool required = true;
    };
  };

  static ValidationResult validate(const json& j, const std::string& path = "") {
    ValidationResult result;
    if (!j.is_object()) { result.add(path, "Expected object"); return result; }
    if (!j.contains("path")) result.add(path.empty() ? "path" : path + ".path", "Required field missing");
    if (!j.contains("layer")) result.add(path.empty() ? "layer" : path + ".layer", "Required field missing");
    if (j.contains("layer")) {
      std::string fp = path.empty() ? "layer" : path + ".layer";
      if (!j["layer"].is_string()) {
        result.add(fp, "Expected string");
      } else {
        const auto& val = j["layer"].get_ref<const std::string&>();
      }
    }
    if (j.contains("offset")) {
      std::string fp = path.empty() ? "offset" : path + ".offset";
      if (!j["offset"].is_object()) {
        result.add(fp, "Expected object");
      } else {
        result.merge(Offset::validate(j["offset"], fp));
      }
    }
    if (j.contains("path")) {
      std::string fp = path.empty() ? "path" : path + ".path";
      if (!j["path"].is_string()) {
        result.add(fp, "Expected string");
      } else {
        const auto& val = j["path"].get_ref<const std::string&>();
      }
    }
    return result;
  }

  static LayersItem fromJson(const json& j) {
    auto vr = validate(j);
    if (!vr.valid()) throw std::runtime_error(vr.summary());
    LayersItem obj;
    obj.setLayer(j.at("layer").get<std::string>());
    if (j.contains("offset")) {
      obj.setOffset(Offset::fromJson(j["offset"]));
    }
    obj.setPath(j.at("path").get<std::string>());
    return obj;
  }

  const std::string& getLayer() const { return layer_; }
  std::string& getLayer() { return layer_; }
  void setLayer(const std::string& value) { layer_ = value; }

  bool hasOffset() const { return offset_.has_value(); }
  const Offset& getOffset() const { return offset_.value(); }
  Offset& getOffset() { return offset_.value(); }
  void setOffset(const Offset& value) { offset_ = value; }

  const std::string& getPath() const { return path_; }
  std::string& getPath() { return path_; }
  void setPath(const std::string& value) { path_ = value; }

private:
  std::string layer_;
  std::optional<Offset> offset_;
  std::string path_;
};

struct SubSpritesItem : public JsonValue {
  struct Properties {
    struct GridPos {
      static const char* name() { return "gridPos"; }
      static constexpr bool required = false;
    };
    struct Layers {
      static const char* name() { return "layers"; }
      static constexpr bool required = true;
    };
  };

  static ValidationResult validate(const json& j, const std::string& path = "") {
    ValidationResult result;
    if (!j.is_object()) { result.add(path, "Expected object"); return result; }
    if (!j.contains("layers")) result.add(path.empty() ? "layers" : path + ".layers", "Required field missing");
    if (j.contains("gridPos")) {
      std::string fp = path.empty() ? "gridPos" : path + ".gridPos";
      if (!j["gridPos"].is_object()) {
        result.add(fp, "Expected object");
      } else {
        result.merge(GridPos::validate(j["gridPos"], fp));
      }
    }
    if (j.contains("layers")) {
      std::string fp = path.empty() ? "layers" : path + ".layers";
      if (!j["layers"].is_array()) {
        result.add(fp, "Expected array");
      } else {
        const auto& arr = j["layers"];
        for (size_t i = 0; i < arr.size(); ++i) {
          std::string ip = fp + "[" + std::to_string(i) + "]";
          if (!arr[i].is_object()) result.add(ip, "Expected object");
          else result.merge(LayersItem::validate(arr[i], ip));
        }
      }
    }
    return result;
  }

  static SubSpritesItem fromJson(const json& j) {
    auto vr = validate(j);
    if (!vr.valid()) throw std::runtime_error(vr.summary());
    SubSpritesItem obj;
    if (j.contains("gridPos")) {
      obj.setGridPos(GridPos::fromJson(j["gridPos"]));
    }
    { std::vector<LayersItem> items; for (const auto& e : j.at("layers")) items.push_back(LayersItem::fromJson(e)); obj.setLayers(items); }
    return obj;
  }

  bool hasGridPos() const { return gridPos_.has_value(); }
  const GridPos& getGridPos() const { return gridPos_.value(); }
  GridPos& getGridPos() { return gridPos_.value(); }
  void setGridPos(const GridPos& value) { gridPos_ = value; }

  const std::vector<LayersItem>& getLayers() const { return layers_; }
  std::vector<LayersItem>& getLayers() { return layers_; }
  void setLayers(const std::vector<LayersItem>& value) { layers_ = value; }

private:
  std::optional<GridPos> gridPos_;
  std::vector<LayersItem> layers_;
};

struct SpriteComponent : public JsonValue {
  struct Properties {
    struct Scaling {
      static const char* name() { return "scaling"; }
      static constexpr bool required = false;
    };
    struct SubSprites {
      static const char* name() { return "subSprites"; }
      static constexpr bool required = true;
    };
    struct Type {
      static const char* name() { return "type"; }
      static constexpr bool required = true;
      static const char* constValue() { return "SpriteComponent"; }
    };
  };

  static ValidationResult validate(const json& j, const std::string& path = "") {
    ValidationResult result;
    if (!j.is_object()) { result.add(path, "Expected object"); return result; }
    if (!j.contains("type")) result.add(path.empty() ? "type" : path + ".type", "Required field missing");
    if (!j.contains("subSprites")) result.add(path.empty() ? "subSprites" : path + ".subSprites", "Required field missing");
    if (j.contains("scaling")) {
      std::string fp = path.empty() ? "scaling" : path + ".scaling";
      if (!j["scaling"].is_number()) {
        result.add(fp, "Expected number");
      } else {
        double val = j["scaling"].get<double>();
      }
    }
    if (j.contains("subSprites")) {
      std::string fp = path.empty() ? "subSprites" : path + ".subSprites";
      if (!j["subSprites"].is_array()) {
        result.add(fp, "Expected array");
      } else {
        const auto& arr = j["subSprites"];
        for (size_t i = 0; i < arr.size(); ++i) {
          std::string ip = fp + "[" + std::to_string(i) + "]";
          if (!arr[i].is_object()) result.add(ip, "Expected object");
          else result.merge(SubSpritesItem::validate(arr[i], ip));
        }
      }
    }
    if (j.contains("type")) {
      std::string fp = path.empty() ? "type" : path + ".type";
      if (!j["type"].is_string()) {
        result.add(fp, "Expected string");
      } else {
        const auto& val = j["type"].get_ref<const std::string&>();
        if (val != "SpriteComponent") result.add(fp, "Value does not match const");
      }
    }
    return result;
  }

  static SpriteComponent fromJson(const json& j) {
    auto vr = validate(j);
    if (!vr.valid()) throw std::runtime_error(vr.summary());
    SpriteComponent obj;
    if (j.contains("scaling")) {
      obj.setScaling(j["scaling"].get<double>());
    }
    { std::vector<SubSpritesItem> items; for (const auto& e : j.at("subSprites")) items.push_back(SubSpritesItem::fromJson(e)); obj.setSubSprites(items); }
    obj.setType(j.at("type").get<std::string>());
    return obj;
  }

  bool hasScaling() const { return scaling_.has_value(); }
  double getScaling() const { return scaling_.value(); }
  void setScaling(double value) { scaling_ = value; }

  const std::vector<SubSpritesItem>& getSubSprites() const { return subSprites_; }
  std::vector<SubSpritesItem>& getSubSprites() { return subSprites_; }
  void setSubSprites(const std::vector<SubSpritesItem>& value) { subSprites_ = value; }

  const std::string& getType() const { return type_; }
  std::string& getType() { return type_; }
  void setType(const std::string& value) { type_ = value; }

private:
  std::optional<double> scaling_;
  std::vector<SubSpritesItem> subSprites_;
  std::string type_;
};

struct SeekPrimaryTargetTag : public JsonValue {
  struct Properties {
    struct Type {
      static const char* name() { return "type"; }
      static constexpr bool required = true;
      static const char* constValue() { return "SeekPrimaryTargetTag"; }
    };
  };

  static ValidationResult validate(const json& j, const std::string& path = "") {
    ValidationResult result;
    if (!j.is_object()) { result.add(path, "Expected object"); return result; }
    if (!j.contains("type")) result.add(path.empty() ? "type" : path + ".type", "Required field missing");
    if (j.contains("type")) {
      std::string fp = path.empty() ? "type" : path + ".type";
      if (!j["type"].is_string()) {
        result.add(fp, "Expected string");
      } else {
        const auto& val = j["type"].get_ref<const std::string&>();
        if (val != "SeekPrimaryTargetTag") result.add(fp, "Value does not match const");
      }
    }
    return result;
  }

  static SeekPrimaryTargetTag fromJson(const json& j) {
    auto vr = validate(j);
    if (!vr.valid()) throw std::runtime_error(vr.summary());
    SeekPrimaryTargetTag obj;
    obj.setType(j.at("type").get<std::string>());
    return obj;
  }

  const std::string& getType() const { return type_; }
  std::string& getType() { return type_; }
  void setType(const std::string& value) { type_ = value; }

private:
  std::string type_;
};

struct HealthComponent : public JsonValue {
  struct Properties {
    struct Health {
      static const char* name() { return "health"; }
      static constexpr bool required = true;
    };
    struct Type {
      static const char* name() { return "type"; }
      static constexpr bool required = true;
      static const char* constValue() { return "HealthComponent"; }
    };
  };

  static ValidationResult validate(const json& j, const std::string& path = "") {
    ValidationResult result;
    if (!j.is_object()) { result.add(path, "Expected object"); return result; }
    if (!j.contains("type")) result.add(path.empty() ? "type" : path + ".type", "Required field missing");
    if (!j.contains("health")) result.add(path.empty() ? "health" : path + ".health", "Required field missing");
    if (j.contains("health")) {
      std::string fp = path.empty() ? "health" : path + ".health";
      if (!j["health"].is_number()) {
        result.add(fp, "Expected number");
      } else {
        double val = j["health"].get<double>();
      }
    }
    if (j.contains("type")) {
      std::string fp = path.empty() ? "type" : path + ".type";
      if (!j["type"].is_string()) {
        result.add(fp, "Expected string");
      } else {
        const auto& val = j["type"].get_ref<const std::string&>();
        if (val != "HealthComponent") result.add(fp, "Value does not match const");
      }
    }
    return result;
  }

  static HealthComponent fromJson(const json& j) {
    auto vr = validate(j);
    if (!vr.valid()) throw std::runtime_error(vr.summary());
    HealthComponent obj;
    obj.setHealth(j.at("health").get<double>());
    obj.setType(j.at("type").get<std::string>());
    return obj;
  }

  double getHealth() const { return health_; }
  void setHealth(double value) { health_ = value; }

  const std::string& getType() const { return type_; }
  std::string& getType() { return type_; }
  void setType(const std::string& value) { type_ = value; }

private:
  double health_{};
  std::string type_;
};

struct ContactDamageComponent : public JsonValue {
  struct Properties {
    struct Damage {
      static const char* name() { return "damage"; }
      static constexpr bool required = true;
    };
    struct Type {
      static const char* name() { return "type"; }
      static constexpr bool required = true;
      static const char* constValue() { return "ContactDamageComponent"; }
    };
  };

  static ValidationResult validate(const json& j, const std::string& path = "") {
    ValidationResult result;
    if (!j.is_object()) { result.add(path, "Expected object"); return result; }
    if (!j.contains("type")) result.add(path.empty() ? "type" : path + ".type", "Required field missing");
    if (!j.contains("damage")) result.add(path.empty() ? "damage" : path + ".damage", "Required field missing");
    if (j.contains("damage")) {
      std::string fp = path.empty() ? "damage" : path + ".damage";
      if (!j["damage"].is_number()) {
        result.add(fp, "Expected number");
      } else {
        double val = j["damage"].get<double>();
      }
    }
    if (j.contains("type")) {
      std::string fp = path.empty() ? "type" : path + ".type";
      if (!j["type"].is_string()) {
        result.add(fp, "Expected string");
      } else {
        const auto& val = j["type"].get_ref<const std::string&>();
        if (val != "ContactDamageComponent") result.add(fp, "Value does not match const");
      }
    }
    return result;
  }

  static ContactDamageComponent fromJson(const json& j) {
    auto vr = validate(j);
    if (!vr.valid()) throw std::runtime_error(vr.summary());
    ContactDamageComponent obj;
    obj.setDamage(j.at("damage").get<double>());
    obj.setType(j.at("type").get<std::string>());
    return obj;
  }

  double getDamage() const { return damage_; }
  void setDamage(double value) { damage_ = value; }

  const std::string& getType() const { return type_; }
  std::string& getType() { return type_; }
  void setType(const std::string& value) { type_ = value; }

private:
  double damage_{};
  std::string type_;
};

struct Shape : public JsonValue {
  struct Properties {
    struct Height {
      static const char* name() { return "height"; }
      static constexpr bool required = false;
    };
    struct Radius {
      static const char* name() { return "radius"; }
      static constexpr bool required = false;
    };
    struct ShapeType {
      static const char* name() { return "shapeType"; }
      static constexpr bool required = true;
    };
    struct Width {
      static const char* name() { return "width"; }
      static constexpr bool required = false;
    };
  };

  static ValidationResult validate(const json& j, const std::string& path = "") {
    ValidationResult result;
    if (!j.is_object()) { result.add(path, "Expected object"); return result; }
    if (!j.contains("shapeType")) result.add(path.empty() ? "shapeType" : path + ".shapeType", "Required field missing");
    if (j.contains("height")) {
      std::string fp = path.empty() ? "height" : path + ".height";
      if (!j["height"].is_number()) {
        result.add(fp, "Expected number");
      } else {
        double val = j["height"].get<double>();
      }
    }
    if (j.contains("radius")) {
      std::string fp = path.empty() ? "radius" : path + ".radius";
      if (!j["radius"].is_number()) {
        result.add(fp, "Expected number");
      } else {
        double val = j["radius"].get<double>();
      }
    }
    if (j.contains("shapeType")) {
      std::string fp = path.empty() ? "shapeType" : path + ".shapeType";
      if (!j["shapeType"].is_string()) {
        result.add(fp, "Expected string");
      } else {
        const auto& val = j["shapeType"].get_ref<const std::string&>();
        { bool ok = val == "Circle" || val == "Box"; if (!ok) result.add(fp, "Value not in enum"); }
      }
    }
    if (j.contains("width")) {
      std::string fp = path.empty() ? "width" : path + ".width";
      if (!j["width"].is_number()) {
        result.add(fp, "Expected number");
      } else {
        double val = j["width"].get<double>();
      }
    }
    return result;
  }

  static Shape fromJson(const json& j) {
    auto vr = validate(j);
    if (!vr.valid()) throw std::runtime_error(vr.summary());
    Shape obj;
    if (j.contains("height")) {
      obj.setHeight(j["height"].get<double>());
    }
    if (j.contains("radius")) {
      obj.setRadius(j["radius"].get<double>());
    }
    obj.setShapeType(j.at("shapeType").get<std::string>());
    if (j.contains("width")) {
      obj.setWidth(j["width"].get<double>());
    }
    return obj;
  }

  bool hasHeight() const { return height_.has_value(); }
  double getHeight() const { return height_.value(); }
  void setHeight(double value) { height_ = value; }

  bool hasRadius() const { return radius_.has_value(); }
  double getRadius() const { return radius_.value(); }
  void setRadius(double value) { radius_ = value; }

  const std::string& getShapeType() const { return shapeType_; }
  std::string& getShapeType() { return shapeType_; }
  void setShapeType(const std::string& value) { shapeType_ = value; }

  bool hasWidth() const { return width_.has_value(); }
  double getWidth() const { return width_.value(); }
  void setWidth(double value) { width_ = value; }

private:
  std::optional<double> height_;
  std::optional<double> radius_;
  std::string shapeType_;
  std::optional<double> width_;
};

struct ShapesItem : public JsonValue {
  struct Properties {
    struct CategoryMask {
      static const char* name() { return "categoryMask"; }
      static constexpr bool required = true;
    };
    struct CollisionMask {
      static const char* name() { return "collisionMask"; }
      static constexpr bool required = true;
    };
    struct Density {
      static const char* name() { return "density"; }
      static constexpr bool required = true;
    };
    struct EnableContactEvents {
      static const char* name() { return "enableContactEvents"; }
      static constexpr bool required = true;
    };
    struct Shape {
      static const char* name() { return "shape"; }
      static constexpr bool required = true;
    };
  };

  static ValidationResult validate(const json& j, const std::string& path = "") {
    ValidationResult result;
    if (!j.is_object()) { result.add(path, "Expected object"); return result; }
    if (!j.contains("enableContactEvents")) result.add(path.empty() ? "enableContactEvents" : path + ".enableContactEvents", "Required field missing");
    if (!j.contains("categoryMask")) result.add(path.empty() ? "categoryMask" : path + ".categoryMask", "Required field missing");
    if (!j.contains("collisionMask")) result.add(path.empty() ? "collisionMask" : path + ".collisionMask", "Required field missing");
    if (!j.contains("density")) result.add(path.empty() ? "density" : path + ".density", "Required field missing");
    if (!j.contains("shape")) result.add(path.empty() ? "shape" : path + ".shape", "Required field missing");
    if (j.contains("categoryMask")) {
      std::string fp = path.empty() ? "categoryMask" : path + ".categoryMask";
      if (!j["categoryMask"].is_array()) {
        result.add(fp, "Expected array");
      } else {
        const auto& arr = j["categoryMask"];
        for (size_t i = 0; i < arr.size(); ++i) {
          if (!arr[i].is_string()) result.add(fp + "[" + std::to_string(i) + "]", "Expected string");
        }
      }
    }
    if (j.contains("collisionMask")) {
      std::string fp = path.empty() ? "collisionMask" : path + ".collisionMask";
      if (!j["collisionMask"].is_array()) {
        result.add(fp, "Expected array");
      } else {
        const auto& arr = j["collisionMask"];
        for (size_t i = 0; i < arr.size(); ++i) {
          if (!arr[i].is_string()) result.add(fp + "[" + std::to_string(i) + "]", "Expected string");
        }
      }
    }
    if (j.contains("density")) {
      std::string fp = path.empty() ? "density" : path + ".density";
      if (!j["density"].is_number()) {
        result.add(fp, "Expected number");
      } else {
        double val = j["density"].get<double>();
      }
    }
    if (j.contains("enableContactEvents")) {
      std::string fp = path.empty() ? "enableContactEvents" : path + ".enableContactEvents";
      if (!j["enableContactEvents"].is_boolean()) {
        result.add(fp, "Expected boolean");
      }
    }
    if (j.contains("shape")) {
      std::string fp = path.empty() ? "shape" : path + ".shape";
      if (!j["shape"].is_object()) {
        result.add(fp, "Expected object");
      } else {
        result.merge(Shape::validate(j["shape"], fp));
      }
    }
    return result;
  }

  static ShapesItem fromJson(const json& j) {
    auto vr = validate(j);
    if (!vr.valid()) throw std::runtime_error(vr.summary());
    ShapesItem obj;
    obj.setCategoryMask(j.at("categoryMask").get<std::vector<std::string>>());
    obj.setCollisionMask(j.at("collisionMask").get<std::vector<std::string>>());
    obj.setDensity(j.at("density").get<double>());
    obj.setEnableContactEvents(j.at("enableContactEvents").get<bool>());
    obj.setShape(Shape::fromJson(j.at("shape")));
    return obj;
  }

  const std::vector<std::string>& getCategoryMask() const { return categoryMask_; }
  std::vector<std::string>& getCategoryMask() { return categoryMask_; }
  void setCategoryMask(const std::vector<std::string>& value) { categoryMask_ = value; }

  const std::vector<std::string>& getCollisionMask() const { return collisionMask_; }
  std::vector<std::string>& getCollisionMask() { return collisionMask_; }
  void setCollisionMask(const std::vector<std::string>& value) { collisionMask_ = value; }

  double getDensity() const { return density_; }
  void setDensity(double value) { density_ = value; }

  bool getEnableContactEvents() const { return enableContactEvents_; }
  void setEnableContactEvents(bool value) { enableContactEvents_ = value; }

  const Shape& getShape() const { return shape_; }
  Shape& getShape() { return shape_; }
  void setShape(const Shape& value) { shape_ = value; }

private:
  std::vector<std::string> categoryMask_;
  std::vector<std::string> collisionMask_;
  double density_{};
  bool enableContactEvents_{};
  Shape shape_;
};

struct BodyComponent : public JsonValue {
  struct Properties {
    struct BodyType {
      static const char* name() { return "bodyType"; }
      static constexpr bool required = true;
    };
    struct LinearDamping {
      static const char* name() { return "linearDamping"; }
      static constexpr bool required = true;
    };
    struct Shapes {
      static const char* name() { return "shapes"; }
      static constexpr bool required = true;
    };
    struct Type {
      static const char* name() { return "type"; }
      static constexpr bool required = true;
      static const char* constValue() { return "BodyComponent"; }
    };
  };

  static ValidationResult validate(const json& j, const std::string& path = "") {
    ValidationResult result;
    if (!j.is_object()) { result.add(path, "Expected object"); return result; }
    if (!j.contains("type")) result.add(path.empty() ? "type" : path + ".type", "Required field missing");
    if (!j.contains("bodyType")) result.add(path.empty() ? "bodyType" : path + ".bodyType", "Required field missing");
    if (!j.contains("linearDamping")) result.add(path.empty() ? "linearDamping" : path + ".linearDamping", "Required field missing");
    if (!j.contains("shapes")) result.add(path.empty() ? "shapes" : path + ".shapes", "Required field missing");
    if (j.contains("bodyType")) {
      std::string fp = path.empty() ? "bodyType" : path + ".bodyType";
      if (!j["bodyType"].is_string()) {
        result.add(fp, "Expected string");
      } else {
        const auto& val = j["bodyType"].get_ref<const std::string&>();
        { bool ok = val == "dynamic" || val == "static" || val == "kinematic"; if (!ok) result.add(fp, "Value not in enum"); }
      }
    }
    if (j.contains("linearDamping")) {
      std::string fp = path.empty() ? "linearDamping" : path + ".linearDamping";
      if (!j["linearDamping"].is_number()) {
        result.add(fp, "Expected number");
      } else {
        double val = j["linearDamping"].get<double>();
      }
    }
    if (j.contains("shapes")) {
      std::string fp = path.empty() ? "shapes" : path + ".shapes";
      if (!j["shapes"].is_array()) {
        result.add(fp, "Expected array");
      } else {
        const auto& arr = j["shapes"];
        for (size_t i = 0; i < arr.size(); ++i) {
          std::string ip = fp + "[" + std::to_string(i) + "]";
          if (!arr[i].is_object()) result.add(ip, "Expected object");
          else result.merge(ShapesItem::validate(arr[i], ip));
        }
      }
    }
    if (j.contains("type")) {
      std::string fp = path.empty() ? "type" : path + ".type";
      if (!j["type"].is_string()) {
        result.add(fp, "Expected string");
      } else {
        const auto& val = j["type"].get_ref<const std::string&>();
        if (val != "BodyComponent") result.add(fp, "Value does not match const");
      }
    }
    return result;
  }

  static BodyComponent fromJson(const json& j) {
    auto vr = validate(j);
    if (!vr.valid()) throw std::runtime_error(vr.summary());
    BodyComponent obj;
    obj.setBodyType(j.at("bodyType").get<std::string>());
    obj.setLinearDamping(j.at("linearDamping").get<double>());
    { std::vector<ShapesItem> items; for (const auto& e : j.at("shapes")) items.push_back(ShapesItem::fromJson(e)); obj.setShapes(items); }
    obj.setType(j.at("type").get<std::string>());
    return obj;
  }

  const std::string& getBodyType() const { return bodyType_; }
  std::string& getBodyType() { return bodyType_; }
  void setBodyType(const std::string& value) { bodyType_ = value; }

  double getLinearDamping() const { return linearDamping_; }
  void setLinearDamping(double value) { linearDamping_ = value; }

  const std::vector<ShapesItem>& getShapes() const { return shapes_; }
  std::vector<ShapesItem>& getShapes() { return shapes_; }
  void setShapes(const std::vector<ShapesItem>& value) { shapes_ = value; }

  const std::string& getType() const { return type_; }
  std::string& getType() { return type_; }
  void setType(const std::string& value) { type_ = value; }

private:
  std::string bodyType_;
  double linearDamping_{};
  std::vector<ShapesItem> shapes_;
  std::string type_;
};

struct Material : public JsonValue {
  struct Properties {
    struct Friction {
      static const char* name() { return "friction"; }
      static constexpr bool required = true;
    };
    struct Restitution {
      static const char* name() { return "restitution"; }
      static constexpr bool required = true;
    };
  };

  static ValidationResult validate(const json& j, const std::string& path = "") {
    ValidationResult result;
    if (!j.is_object()) { result.add(path, "Expected object"); return result; }
    if (!j.contains("friction")) result.add(path.empty() ? "friction" : path + ".friction", "Required field missing");
    if (!j.contains("restitution")) result.add(path.empty() ? "restitution" : path + ".restitution", "Required field missing");
    if (j.contains("friction")) {
      std::string fp = path.empty() ? "friction" : path + ".friction";
      if (!j["friction"].is_number()) {
        result.add(fp, "Expected number");
      } else {
        double val = j["friction"].get<double>();
      }
    }
    if (j.contains("restitution")) {
      std::string fp = path.empty() ? "restitution" : path + ".restitution";
      if (!j["restitution"].is_number()) {
        result.add(fp, "Expected number");
      } else {
        double val = j["restitution"].get<double>();
      }
    }
    return result;
  }

  static Material fromJson(const json& j) {
    auto vr = validate(j);
    if (!vr.valid()) throw std::runtime_error(vr.summary());
    Material obj;
    obj.setFriction(j.at("friction").get<double>());
    obj.setRestitution(j.at("restitution").get<double>());
    return obj;
  }

  double getFriction() const { return friction_; }
  void setFriction(double value) { friction_ = value; }

  double getRestitution() const { return restitution_; }
  void setRestitution(double value) { restitution_ = value; }

private:
  double friction_{};
  double restitution_{};
};

struct TileComponent : public JsonValue {
  struct Properties {
    struct Collidable {
      static const char* name() { return "collidable"; }
      static constexpr bool required = false;
    };
    struct Material {
      static const char* name() { return "material"; }
      static constexpr bool required = false;
    };
    struct Type {
      static const char* name() { return "type"; }
      static constexpr bool required = false;
      static const char* constValue() { return "TileComponent"; }
    };
  };

  static ValidationResult validate(const json& j, const std::string& path = "") {
    ValidationResult result;
    if (!j.is_object()) { result.add(path, "Expected object"); return result; }
    if (j.contains("collidable")) {
      std::string fp = path.empty() ? "collidable" : path + ".collidable";
      if (!j["collidable"].is_boolean()) {
        result.add(fp, "Expected boolean");
      }
    }
    if (j.contains("material")) {
      std::string fp = path.empty() ? "material" : path + ".material";
      if (!j["material"].is_object()) {
        result.add(fp, "Expected object");
      } else {
        result.merge(Material::validate(j["material"], fp));
      }
    }
    if (j.contains("type")) {
      std::string fp = path.empty() ? "type" : path + ".type";
      if (!j["type"].is_string()) {
        result.add(fp, "Expected string");
      } else {
        const auto& val = j["type"].get_ref<const std::string&>();
        if (val != "TileComponent") result.add(fp, "Value does not match const");
      }
    }
    return result;
  }

  static TileComponent fromJson(const json& j) {
    auto vr = validate(j);
    if (!vr.valid()) throw std::runtime_error(vr.summary());
    TileComponent obj;
    if (j.contains("collidable")) {
      obj.setCollidable(j["collidable"].get<bool>());
    }
    if (j.contains("material")) {
      obj.setMaterial(Material::fromJson(j["material"]));
    }
    if (j.contains("type")) {
      obj.setType(j["type"].get<std::string>());
    }
    return obj;
  }

  bool hasCollidable() const { return collidable_.has_value(); }
  bool getCollidable() const { return collidable_.value(); }
  void setCollidable(bool value) { collidable_ = value; }

  bool hasMaterial() const { return material_.has_value(); }
  const Material& getMaterial() const { return material_.value(); }
  Material& getMaterial() { return material_.value(); }
  void setMaterial(const Material& value) { material_ = value; }

  bool hasType() const { return type_.has_value(); }
  const std::string& getType() const { return type_.value(); }
  std::string& getType() { return type_.value(); }
  void setType(const std::string& value) { type_ = value; }

private:
  std::optional<bool> collidable_;
  std::optional<Material> material_;
  std::optional<std::string> type_;
};

struct ArrowComponent : public JsonValue {
  struct Properties {
    struct TileCost {
      static const char* name() { return "tileCost"; }
      static constexpr bool required = false;
    };
    struct Type {
      static const char* name() { return "type"; }
      static constexpr bool required = false;
      static const char* constValue() { return "ArrowComponent"; }
    };
  };

  static ValidationResult validate(const json& j, const std::string& path = "") {
    ValidationResult result;
    if (!j.is_object()) { result.add(path, "Expected object"); return result; }
    if (j.contains("tileCost")) {
      std::string fp = path.empty() ? "tileCost" : path + ".tileCost";
      if (!j["tileCost"].is_number()) {
        result.add(fp, "Expected number");
      } else {
        double val = j["tileCost"].get<double>();
      }
    }
    if (j.contains("type")) {
      std::string fp = path.empty() ? "type" : path + ".type";
      if (!j["type"].is_string()) {
        result.add(fp, "Expected string");
      } else {
        const auto& val = j["type"].get_ref<const std::string&>();
        if (val != "ArrowComponent") result.add(fp, "Value does not match const");
      }
    }
    return result;
  }

  static ArrowComponent fromJson(const json& j) {
    auto vr = validate(j);
    if (!vr.valid()) throw std::runtime_error(vr.summary());
    ArrowComponent obj;
    if (j.contains("tileCost")) {
      obj.setTileCost(j["tileCost"].get<double>());
    }
    if (j.contains("type")) {
      obj.setType(j["type"].get<std::string>());
    }
    return obj;
  }

  bool hasTileCost() const { return tileCost_.has_value(); }
  double getTileCost() const { return tileCost_.value(); }
  void setTileCost(double value) { tileCost_ = value; }

  bool hasType() const { return type_.has_value(); }
  const std::string& getType() const { return type_.value(); }
  std::string& getType() { return type_.value(); }
  void setType(const std::string& value) { type_ = value; }

private:
  std::optional<double> tileCost_;
  std::optional<std::string> type_;
};

struct AnchorPos : public JsonValue {
  struct Properties {
    struct X {
      static const char* name() { return "x"; }
      static constexpr bool required = true;
    };
    struct Y {
      static const char* name() { return "y"; }
      static constexpr bool required = true;
    };
    struct Z {
      static const char* name() { return "z"; }
      static constexpr bool required = true;
    };
  };

  static ValidationResult validate(const json& j, const std::string& path = "") {
    ValidationResult result;
    if (!j.is_object()) { result.add(path, "Expected object"); return result; }
    if (!j.contains("x")) result.add(path.empty() ? "x" : path + ".x", "Required field missing");
    if (!j.contains("y")) result.add(path.empty() ? "y" : path + ".y", "Required field missing");
    if (!j.contains("z")) result.add(path.empty() ? "z" : path + ".z", "Required field missing");
    if (j.contains("x")) {
      std::string fp = path.empty() ? "x" : path + ".x";
      if (!j["x"].is_number()) {
        result.add(fp, "Expected number");
      } else {
        double val = j["x"].get<double>();
      }
    }
    if (j.contains("y")) {
      std::string fp = path.empty() ? "y" : path + ".y";
      if (!j["y"].is_number()) {
        result.add(fp, "Expected number");
      } else {
        double val = j["y"].get<double>();
      }
    }
    if (j.contains("z")) {
      std::string fp = path.empty() ? "z" : path + ".z";
      if (!j["z"].is_number()) {
        result.add(fp, "Expected number");
      } else {
        double val = j["z"].get<double>();
      }
    }
    return result;
  }

  static AnchorPos fromJson(const json& j) {
    auto vr = validate(j);
    if (!vr.valid()) throw std::runtime_error(vr.summary());
    AnchorPos obj;
    obj.setX(j.at("x").get<double>());
    obj.setY(j.at("y").get<double>());
    obj.setZ(j.at("z").get<double>());
    return obj;
  }

  double getX() const { return x_; }
  void setX(double value) { x_ = value; }

  double getY() const { return y_; }
  void setY(double value) { y_ = value; }

  double getZ() const { return z_; }
  void setZ(double value) { z_ = value; }

private:
  double x_{};
  double y_{};
  double z_{};
};

struct OccupiedPositionsItem : public JsonValue {
  struct Properties {
    struct X {
      static const char* name() { return "x"; }
      static constexpr bool required = true;
    };
    struct Y {
      static const char* name() { return "y"; }
      static constexpr bool required = true;
    };
    struct Z {
      static const char* name() { return "z"; }
      static constexpr bool required = true;
    };
  };

  static ValidationResult validate(const json& j, const std::string& path = "") {
    ValidationResult result;
    if (!j.is_object()) { result.add(path, "Expected object"); return result; }
    if (!j.contains("x")) result.add(path.empty() ? "x" : path + ".x", "Required field missing");
    if (!j.contains("y")) result.add(path.empty() ? "y" : path + ".y", "Required field missing");
    if (!j.contains("z")) result.add(path.empty() ? "z" : path + ".z", "Required field missing");
    if (j.contains("x")) {
      std::string fp = path.empty() ? "x" : path + ".x";
      if (!j["x"].is_number()) {
        result.add(fp, "Expected number");
      } else {
        double val = j["x"].get<double>();
      }
    }
    if (j.contains("y")) {
      std::string fp = path.empty() ? "y" : path + ".y";
      if (!j["y"].is_number()) {
        result.add(fp, "Expected number");
      } else {
        double val = j["y"].get<double>();
      }
    }
    if (j.contains("z")) {
      std::string fp = path.empty() ? "z" : path + ".z";
      if (!j["z"].is_number()) {
        result.add(fp, "Expected number");
      } else {
        double val = j["z"].get<double>();
      }
    }
    return result;
  }

  static OccupiedPositionsItem fromJson(const json& j) {
    auto vr = validate(j);
    if (!vr.valid()) throw std::runtime_error(vr.summary());
    OccupiedPositionsItem obj;
    obj.setX(j.at("x").get<double>());
    obj.setY(j.at("y").get<double>());
    obj.setZ(j.at("z").get<double>());
    return obj;
  }

  double getX() const { return x_; }
  void setX(double value) { x_ = value; }

  double getY() const { return y_; }
  void setY(double value) { y_ = value; }

  double getZ() const { return z_; }
  void setZ(double value) { z_ = value; }

private:
  double x_{};
  double y_{};
  double z_{};
};

struct MultiTileComponent : public JsonValue {
  struct Properties {
    struct AnchorPos {
      static const char* name() { return "anchorPos"; }
      static constexpr bool required = true;
    };
    struct OccupiedPositions {
      static const char* name() { return "occupiedPositions"; }
      static constexpr bool required = true;
    };
    struct Type {
      static const char* name() { return "type"; }
      static constexpr bool required = true;
      static const char* constValue() { return "MultiTileComponent"; }
    };
  };

  static ValidationResult validate(const json& j, const std::string& path = "") {
    ValidationResult result;
    if (!j.is_object()) { result.add(path, "Expected object"); return result; }
    if (!j.contains("type")) result.add(path.empty() ? "type" : path + ".type", "Required field missing");
    if (!j.contains("occupiedPositions")) result.add(path.empty() ? "occupiedPositions" : path + ".occupiedPositions", "Required field missing");
    if (!j.contains("anchorPos")) result.add(path.empty() ? "anchorPos" : path + ".anchorPos", "Required field missing");
    if (j.contains("anchorPos")) {
      std::string fp = path.empty() ? "anchorPos" : path + ".anchorPos";
      if (!j["anchorPos"].is_object()) {
        result.add(fp, "Expected object");
      } else {
        result.merge(AnchorPos::validate(j["anchorPos"], fp));
      }
    }
    if (j.contains("occupiedPositions")) {
      std::string fp = path.empty() ? "occupiedPositions" : path + ".occupiedPositions";
      if (!j["occupiedPositions"].is_array()) {
        result.add(fp, "Expected array");
      } else {
        const auto& arr = j["occupiedPositions"];
        for (size_t i = 0; i < arr.size(); ++i) {
          std::string ip = fp + "[" + std::to_string(i) + "]";
          if (!arr[i].is_object()) result.add(ip, "Expected object");
          else result.merge(OccupiedPositionsItem::validate(arr[i], ip));
        }
      }
    }
    if (j.contains("type")) {
      std::string fp = path.empty() ? "type" : path + ".type";
      if (!j["type"].is_string()) {
        result.add(fp, "Expected string");
      } else {
        const auto& val = j["type"].get_ref<const std::string&>();
        if (val != "MultiTileComponent") result.add(fp, "Value does not match const");
      }
    }
    return result;
  }

  static MultiTileComponent fromJson(const json& j) {
    auto vr = validate(j);
    if (!vr.valid()) throw std::runtime_error(vr.summary());
    MultiTileComponent obj;
    obj.setAnchorPos(AnchorPos::fromJson(j.at("anchorPos")));
    { std::vector<OccupiedPositionsItem> items; for (const auto& e : j.at("occupiedPositions")) items.push_back(OccupiedPositionsItem::fromJson(e)); obj.setOccupiedPositions(items); }
    obj.setType(j.at("type").get<std::string>());
    return obj;
  }

  const AnchorPos& getAnchorPos() const { return anchorPos_; }
  AnchorPos& getAnchorPos() { return anchorPos_; }
  void setAnchorPos(const AnchorPos& value) { anchorPos_ = value; }

  const std::vector<OccupiedPositionsItem>& getOccupiedPositions() const { return occupiedPositions_; }
  std::vector<OccupiedPositionsItem>& getOccupiedPositions() { return occupiedPositions_; }
  void setOccupiedPositions(const std::vector<OccupiedPositionsItem>& value) { occupiedPositions_ = value; }

  const std::string& getType() const { return type_; }
  std::string& getType() { return type_; }
  void setType(const std::string& value) { type_ = value; }

private:
  AnchorPos anchorPos_;
  std::vector<OccupiedPositionsItem> occupiedPositions_;
  std::string type_;
};

struct TurretComponent : public JsonValue {
  struct Properties {
    struct BulletDamage {
      static const char* name() { return "bulletDamage"; }
      static constexpr bool required = false;
    };
    struct BulletRadius {
      static const char* name() { return "bulletRadius"; }
      static constexpr bool required = false;
    };
    struct FireRate {
      static const char* name() { return "fireRate"; }
      static constexpr bool required = false;
    };
    struct MuzzleVelocity {
      static const char* name() { return "muzzleVelocity"; }
      static constexpr bool required = false;
    };
    struct Radius {
      static const char* name() { return "radius"; }
      static constexpr bool required = false;
    };
    struct ShootRange {
      static const char* name() { return "shootRange"; }
      static constexpr bool required = false;
    };
    struct StopRange {
      static const char* name() { return "stopRange"; }
      static constexpr bool required = false;
    };
    struct TurnSpeed {
      static const char* name() { return "turnSpeed"; }
      static constexpr bool required = false;
    };
    struct Type {
      static const char* name() { return "type"; }
      static constexpr bool required = true;
      static const char* constValue() { return "TurretComponent"; }
    };
  };

  static ValidationResult validate(const json& j, const std::string& path = "") {
    ValidationResult result;
    if (!j.is_object()) { result.add(path, "Expected object"); return result; }
    if (!j.contains("type")) result.add(path.empty() ? "type" : path + ".type", "Required field missing");
    if (j.contains("bulletDamage")) {
      std::string fp = path.empty() ? "bulletDamage" : path + ".bulletDamage";
      if (!j["bulletDamage"].is_number()) {
        result.add(fp, "Expected number");
      } else {
        double val = j["bulletDamage"].get<double>();
      }
    }
    if (j.contains("bulletRadius")) {
      std::string fp = path.empty() ? "bulletRadius" : path + ".bulletRadius";
      if (!j["bulletRadius"].is_number()) {
        result.add(fp, "Expected number");
      } else {
        double val = j["bulletRadius"].get<double>();
      }
    }
    if (j.contains("fireRate")) {
      std::string fp = path.empty() ? "fireRate" : path + ".fireRate";
      if (!j["fireRate"].is_number()) {
        result.add(fp, "Expected number");
      } else {
        double val = j["fireRate"].get<double>();
      }
    }
    if (j.contains("muzzleVelocity")) {
      std::string fp = path.empty() ? "muzzleVelocity" : path + ".muzzleVelocity";
      if (!j["muzzleVelocity"].is_number()) {
        result.add(fp, "Expected number");
      } else {
        double val = j["muzzleVelocity"].get<double>();
      }
    }
    if (j.contains("radius")) {
      std::string fp = path.empty() ? "radius" : path + ".radius";
      if (!j["radius"].is_number()) {
        result.add(fp, "Expected number");
      } else {
        double val = j["radius"].get<double>();
      }
    }
    if (j.contains("shootRange")) {
      std::string fp = path.empty() ? "shootRange" : path + ".shootRange";
      if (!j["shootRange"].is_number()) {
        result.add(fp, "Expected number");
      } else {
        double val = j["shootRange"].get<double>();
      }
    }
    if (j.contains("stopRange")) {
      std::string fp = path.empty() ? "stopRange" : path + ".stopRange";
      if (!j["stopRange"].is_number()) {
        result.add(fp, "Expected number");
      } else {
        double val = j["stopRange"].get<double>();
      }
    }
    if (j.contains("turnSpeed")) {
      std::string fp = path.empty() ? "turnSpeed" : path + ".turnSpeed";
      if (!j["turnSpeed"].is_number()) {
        result.add(fp, "Expected number");
      } else {
        double val = j["turnSpeed"].get<double>();
      }
    }
    if (j.contains("type")) {
      std::string fp = path.empty() ? "type" : path + ".type";
      if (!j["type"].is_string()) {
        result.add(fp, "Expected string");
      } else {
        const auto& val = j["type"].get_ref<const std::string&>();
        if (val != "TurretComponent") result.add(fp, "Value does not match const");
      }
    }
    return result;
  }

  static TurretComponent fromJson(const json& j) {
    auto vr = validate(j);
    if (!vr.valid()) throw std::runtime_error(vr.summary());
    TurretComponent obj;
    if (j.contains("bulletDamage")) {
      obj.setBulletDamage(j["bulletDamage"].get<double>());
    }
    if (j.contains("bulletRadius")) {
      obj.setBulletRadius(j["bulletRadius"].get<double>());
    }
    if (j.contains("fireRate")) {
      obj.setFireRate(j["fireRate"].get<double>());
    }
    if (j.contains("muzzleVelocity")) {
      obj.setMuzzleVelocity(j["muzzleVelocity"].get<double>());
    }
    if (j.contains("radius")) {
      obj.setRadius(j["radius"].get<double>());
    }
    if (j.contains("shootRange")) {
      obj.setShootRange(j["shootRange"].get<double>());
    }
    if (j.contains("stopRange")) {
      obj.setStopRange(j["stopRange"].get<double>());
    }
    if (j.contains("turnSpeed")) {
      obj.setTurnSpeed(j["turnSpeed"].get<double>());
    }
    obj.setType(j.at("type").get<std::string>());
    return obj;
  }

  bool hasBulletDamage() const { return bulletDamage_.has_value(); }
  double getBulletDamage() const { return bulletDamage_.value(); }
  void setBulletDamage(double value) { bulletDamage_ = value; }

  bool hasBulletRadius() const { return bulletRadius_.has_value(); }
  double getBulletRadius() const { return bulletRadius_.value(); }
  void setBulletRadius(double value) { bulletRadius_ = value; }

  bool hasFireRate() const { return fireRate_.has_value(); }
  double getFireRate() const { return fireRate_.value(); }
  void setFireRate(double value) { fireRate_ = value; }

  bool hasMuzzleVelocity() const { return muzzleVelocity_.has_value(); }
  double getMuzzleVelocity() const { return muzzleVelocity_.value(); }
  void setMuzzleVelocity(double value) { muzzleVelocity_ = value; }

  bool hasRadius() const { return radius_.has_value(); }
  double getRadius() const { return radius_.value(); }
  void setRadius(double value) { radius_ = value; }

  bool hasShootRange() const { return shootRange_.has_value(); }
  double getShootRange() const { return shootRange_.value(); }
  void setShootRange(double value) { shootRange_ = value; }

  bool hasStopRange() const { return stopRange_.has_value(); }
  double getStopRange() const { return stopRange_.value(); }
  void setStopRange(double value) { stopRange_ = value; }

  bool hasTurnSpeed() const { return turnSpeed_.has_value(); }
  double getTurnSpeed() const { return turnSpeed_.value(); }
  void setTurnSpeed(double value) { turnSpeed_ = value; }

  const std::string& getType() const { return type_; }
  std::string& getType() { return type_; }
  void setType(const std::string& value) { type_ = value; }

private:
  std::optional<double> bulletDamage_;
  std::optional<double> bulletRadius_;
  std::optional<double> fireRate_;
  std::optional<double> muzzleVelocity_;
  std::optional<double> radius_;
  std::optional<double> shootRange_;
  std::optional<double> stopRange_;
  std::optional<double> turnSpeed_;
  std::string type_;
};

struct ComponentsItem : public JsonValue {
  using Variant = std::variant<TransformComponent, SpriteComponent, SeekPrimaryTargetTag, HealthComponent, ContactDamageComponent, BodyComponent, TileComponent, ArrowComponent, MultiTileComponent, TurretComponent>;

  static ValidationResult validate(const json& j, const std::string& path = "") {
    ValidationResult result;
    if (!j.is_object()) { result.add(path, "Expected object"); return result; }
    if (!j.contains("type")) {
      result.add(path.empty() ? "type" : path + ".type", "Required discriminator field missing");
      return result;
    }
    if (!j["type"].is_string()) {
      result.add(path.empty() ? "type" : path + ".type", "Discriminator must be a string");
      return result;
    }
    const auto& disc = j["type"].get_ref<const std::string&>();
    if (disc == "TransformComponent") return TransformComponent::validate(j, path);
    else if (disc == "SpriteComponent") return SpriteComponent::validate(j, path);
    else if (disc == "SeekPrimaryTargetTag") return SeekPrimaryTargetTag::validate(j, path);
    else if (disc == "HealthComponent") return HealthComponent::validate(j, path);
    else if (disc == "ContactDamageComponent") return ContactDamageComponent::validate(j, path);
    else if (disc == "BodyComponent") return BodyComponent::validate(j, path);
    else if (disc == "TileComponent") return TileComponent::validate(j, path);
    else if (disc == "ArrowComponent") return ArrowComponent::validate(j, path);
    else if (disc == "MultiTileComponent") return MultiTileComponent::validate(j, path);
    else if (disc == "TurretComponent") return TurretComponent::validate(j, path);
    else result.add(path.empty() ? "type" : path + ".type", "Unknown discriminator value '" + disc + "'");
    return result;
  }

  static ComponentsItem fromJson(const json& j) {
    auto vr = validate(j);
    if (!vr.valid()) throw std::runtime_error(vr.summary());
    ComponentsItem obj;
    const auto& disc = j["type"].get_ref<const std::string&>();
    if (disc == "TransformComponent") obj.variant_ = TransformComponent::fromJson(j);
    else if (disc == "SpriteComponent") obj.variant_ = SpriteComponent::fromJson(j);
    else if (disc == "SeekPrimaryTargetTag") obj.variant_ = SeekPrimaryTargetTag::fromJson(j);
    else if (disc == "HealthComponent") obj.variant_ = HealthComponent::fromJson(j);
    else if (disc == "ContactDamageComponent") obj.variant_ = ContactDamageComponent::fromJson(j);
    else if (disc == "BodyComponent") obj.variant_ = BodyComponent::fromJson(j);
    else if (disc == "TileComponent") obj.variant_ = TileComponent::fromJson(j);
    else if (disc == "ArrowComponent") obj.variant_ = ArrowComponent::fromJson(j);
    else if (disc == "MultiTileComponent") obj.variant_ = MultiTileComponent::fromJson(j);
    else if (disc == "TurretComponent") obj.variant_ = TurretComponent::fromJson(j);
    return obj;
  }

  template <typename T>
  bool holds() const { return std::holds_alternative<T>(variant_); }

  template <typename T>
  const T& get() const { return std::get<T>(variant_); }

  template <typename T>
  T& get() { return std::get<T>(variant_); }

  const Variant& variant() const { return variant_; }
  Variant& variant() { return variant_; }

private:
  Variant variant_;
};

struct Data : public JsonValue {
  struct Properties {
    struct Components {
      static const char* name() { return "components"; }
      static constexpr bool required = true;
    };
    struct Type {
      static const char* name() { return "type"; }
      static constexpr bool required = true;
      static const char* constValue() { return "Entity"; }
    };
  };

  static ValidationResult validate(const json& j, const std::string& path = "") {
    ValidationResult result;
    if (!j.is_object()) { result.add(path, "Expected object"); return result; }
    if (!j.contains("type")) result.add(path.empty() ? "type" : path + ".type", "Required field missing");
    if (!j.contains("components")) result.add(path.empty() ? "components" : path + ".components", "Required field missing");
    if (j.contains("components")) {
      std::string fp = path.empty() ? "components" : path + ".components";
      if (!j["components"].is_array()) {
        result.add(fp, "Expected array");
      } else {
        const auto& arr = j["components"];
        for (size_t i = 0; i < arr.size(); ++i) {
          std::string ip = fp + "[" + std::to_string(i) + "]";
          if (!arr[i].is_object()) result.add(ip, "Expected object");
          else result.merge(ComponentsItem::validate(arr[i], ip));
        }
      }
    }
    if (j.contains("type")) {
      std::string fp = path.empty() ? "type" : path + ".type";
      if (!j["type"].is_string()) {
        result.add(fp, "Expected string");
      } else {
        const auto& val = j["type"].get_ref<const std::string&>();
        if (val != "Entity") result.add(fp, "Value does not match const");
      }
    }
    return result;
  }

  static Data fromJson(const json& j) {
    auto vr = validate(j);
    if (!vr.valid()) throw std::runtime_error(vr.summary());
    Data obj;
    { std::vector<ComponentsItem> items; for (const auto& e : j.at("components")) items.push_back(ComponentsItem::fromJson(e)); obj.setComponents(items); }
    obj.setType(j.at("type").get<std::string>());
    return obj;
  }

  const std::vector<ComponentsItem>& getComponents() const { return components_; }
  std::vector<ComponentsItem>& getComponents() { return components_; }
  void setComponents(const std::vector<ComponentsItem>& value) { components_ = value; }

  const std::string& getType() const { return type_; }
  std::string& getType() { return type_; }
  void setType(const std::string& value) { type_ = value; }

private:
  std::vector<ComponentsItem> components_;
  std::string type_;
};

struct Root : public JsonValue {
  struct Properties {
    struct Data {
      static const char* name() { return "data"; }
      static constexpr bool required = true;
    };
    struct Name {
      static const char* name() { return "name"; }
      static constexpr bool required = true;
    };
  };

  static ValidationResult validate(const json& j, const std::string& path = "") {
    ValidationResult result;
    if (!j.is_object()) { result.add(path, "Expected object"); return result; }
    if (!j.contains("name")) result.add(path.empty() ? "name" : path + ".name", "Required field missing");
    if (!j.contains("data")) result.add(path.empty() ? "data" : path + ".data", "Required field missing");
    if (j.contains("data")) {
      std::string fp = path.empty() ? "data" : path + ".data";
      if (!j["data"].is_object()) {
        result.add(fp, "Expected object");
      } else {
        result.merge(Data::validate(j["data"], fp));
      }
    }
    if (j.contains("name")) {
      std::string fp = path.empty() ? "name" : path + ".name";
      if (!j["name"].is_string()) {
        result.add(fp, "Expected string");
      } else {
        const auto& val = j["name"].get_ref<const std::string&>();
      }
    }
    return result;
  }

  static Root fromJson(const json& j) {
    auto vr = validate(j);
    if (!vr.valid()) throw std::runtime_error(vr.summary());
    Root obj;
    obj.setData(Data::fromJson(j.at("data")));
    obj.setName(j.at("name").get<std::string>());
    return obj;
  }

  const Data& getData() const { return data_; }
  Data& getData() { return data_; }
  void setData(const Data& value) { data_ = value; }

  const std::string& getName() const { return name_; }
  std::string& getName() { return name_; }
  void setName(const std::string& value) { name_ = value; }

private:
  Data data_;
  std::string name_;
};

} // namespace JSchema
