// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: rampage.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#ifndef CAPNP_VERSION
#error "CAPNP_VERSION is not defined, is capnp/generated-header-support.h missing?"
#elif CAPNP_VERSION != 1001000
#error                                                                                                       \
    "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


CAPNP_BEGIN_HEADER

namespace capnp {
  namespace schemas {

    CAPNP_DECLARE_SCHEMA(a9e6ab088fb12bd3);
    CAPNP_DECLARE_SCHEMA(e262e5b439742cac);
    CAPNP_DECLARE_SCHEMA(eed9d9743adb7221);
    CAPNP_DECLARE_SCHEMA(c8d41821c1f3f50a);
    CAPNP_DECLARE_SCHEMA(e9a986a1c0f08f71);
    CAPNP_DECLARE_SCHEMA(d49e55acd79e9157);

  } // namespace schemas
} // namespace capnp

namespace Schema {

  struct Vec2F32 {
    Vec2F32() = delete;

    class Reader;
    class Builder;
    class Pipeline;

    struct _capnpPrivate {
      CAPNP_DECLARE_STRUCT_HEADER(a9e6ab088fb12bd3, 1, 0)
#if !CAPNP_LITE
      static constexpr ::capnp::_::RawBrandedSchema const* brand() {
        return &schema->defaultBrand;
      }
#endif // !CAPNP_LITE
    };
  };

  struct Transform {
    Transform() = delete;

    class Reader;
    class Builder;
    class Pipeline;

    struct _capnpPrivate {
      CAPNP_DECLARE_STRUCT_HEADER(e262e5b439742cac, 1, 1)
#if !CAPNP_LITE
      static constexpr ::capnp::_::RawBrandedSchema const* brand() {
        return &schema->defaultBrand;
      }
#endif // !CAPNP_LITE
    };
  };

  struct Void {
    Void() = delete;

    class Reader;
    class Builder;
    class Pipeline;

    struct _capnpPrivate {
      CAPNP_DECLARE_STRUCT_HEADER(eed9d9743adb7221, 0, 0)
#if !CAPNP_LITE
      static constexpr ::capnp::_::RawBrandedSchema const* brand() {
        return &schema->defaultBrand;
      }
#endif // !CAPNP_LITE
    };
  };

  struct Entity {
    Entity() = delete;

    class Reader;
    class Builder;
    class Pipeline;

    struct _capnpPrivate {
      CAPNP_DECLARE_STRUCT_HEADER(c8d41821c1f3f50a, 1, 2)
#if !CAPNP_LITE
      static constexpr ::capnp::_::RawBrandedSchema const* brand() {
        return &schema->defaultBrand;
      }
#endif // !CAPNP_LITE
    };
  };

  struct ComponentIdName {
    ComponentIdName() = delete;

    class Reader;
    class Builder;
    class Pipeline;

    struct _capnpPrivate {
      CAPNP_DECLARE_STRUCT_HEADER(e9a986a1c0f08f71, 1, 1)
#if !CAPNP_LITE
      static constexpr ::capnp::_::RawBrandedSchema const* brand() {
        return &schema->defaultBrand;
      }
#endif // !CAPNP_LITE
    };
  };

  struct State {
    State() = delete;

    class Reader;
    class Builder;
    class Pipeline;

    struct _capnpPrivate {
      CAPNP_DECLARE_STRUCT_HEADER(d49e55acd79e9157, 0, 2)
#if !CAPNP_LITE
      static constexpr ::capnp::_::RawBrandedSchema const* brand() {
        return &schema->defaultBrand;
      }
#endif // !CAPNP_LITE
    };
  };

  // =======================================================================================

  class Vec2F32::Reader {
  public:
    typedef Vec2F32 Reads;

    Reader() = default;
    inline explicit Reader(::capnp::_::StructReader base) : _reader(base) {}

    inline ::capnp::MessageSize totalSize() const {
      return _reader.totalSize().asPublic();
    }

#if !CAPNP_LITE
    inline ::kj::StringTree toString() const {
      return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
    }
#endif // !CAPNP_LITE

    inline float getX() const;

    inline float getY() const;

  private:
    ::capnp::_::StructReader _reader;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::ToDynamic_;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::_::PointerHelpers;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::List;
    friend class ::capnp::MessageBuilder;
    friend class ::capnp::Orphanage;
  };

  class Vec2F32::Builder {
  public:
    typedef Vec2F32 Builds;

    Builder() = delete; // Deleted to discourage incorrect usage.
                        // You can explicitly initialize to nullptr instead.
    inline Builder(decltype(nullptr)) {}
    inline explicit Builder(::capnp::_::StructBuilder base) : _builder(base) {}
    inline operator Reader() const {
      return Reader(_builder.asReader());
    }
    inline Reader asReader() const {
      return *this;
    }

    inline ::capnp::MessageSize totalSize() const {
      return asReader().totalSize();
    }
#if !CAPNP_LITE
    inline ::kj::StringTree toString() const {
      return asReader().toString();
    }
#endif // !CAPNP_LITE

    inline float getX();
    inline void setX(float value);

    inline float getY();
    inline void setY(float value);

  private:
    ::capnp::_::StructBuilder _builder;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::ToDynamic_;
    friend class ::capnp::Orphanage;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::_::PointerHelpers;
  };

#if !CAPNP_LITE
  class Vec2F32::Pipeline {
  public:
    typedef Vec2F32 Pipelines;

    inline Pipeline(decltype(nullptr)) : _typeless(nullptr) {}
    inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless) : _typeless(kj::mv(typeless)) {}

  private:
    ::capnp::AnyPointer::Pipeline _typeless;
    friend class ::capnp::PipelineHook;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::ToDynamic_;
  };
#endif // !CAPNP_LITE

  class Transform::Reader {
  public:
    typedef Transform Reads;

    Reader() = default;
    inline explicit Reader(::capnp::_::StructReader base) : _reader(base) {}

    inline ::capnp::MessageSize totalSize() const {
      return _reader.totalSize().asPublic();
    }

#if !CAPNP_LITE
    inline ::kj::StringTree toString() const {
      return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
    }
#endif // !CAPNP_LITE

    inline bool hasPos() const;
    inline ::Schema::Vec2F32::Reader getPos() const;

    inline float getRot() const;

  private:
    ::capnp::_::StructReader _reader;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::ToDynamic_;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::_::PointerHelpers;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::List;
    friend class ::capnp::MessageBuilder;
    friend class ::capnp::Orphanage;
  };

  class Transform::Builder {
  public:
    typedef Transform Builds;

    Builder() = delete; // Deleted to discourage incorrect usage.
                        // You can explicitly initialize to nullptr instead.
    inline Builder(decltype(nullptr)) {}
    inline explicit Builder(::capnp::_::StructBuilder base) : _builder(base) {}
    inline operator Reader() const {
      return Reader(_builder.asReader());
    }
    inline Reader asReader() const {
      return *this;
    }

    inline ::capnp::MessageSize totalSize() const {
      return asReader().totalSize();
    }
#if !CAPNP_LITE
    inline ::kj::StringTree toString() const {
      return asReader().toString();
    }
#endif // !CAPNP_LITE

    inline bool hasPos();
    inline ::Schema::Vec2F32::Builder getPos();
    inline void setPos(::Schema::Vec2F32::Reader value);
    inline ::Schema::Vec2F32::Builder initPos();
    inline void adoptPos(::capnp::Orphan<::Schema::Vec2F32>&& value);
    inline ::capnp::Orphan<::Schema::Vec2F32> disownPos();

    inline float getRot();
    inline void setRot(float value);

  private:
    ::capnp::_::StructBuilder _builder;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::ToDynamic_;
    friend class ::capnp::Orphanage;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::_::PointerHelpers;
  };

#if !CAPNP_LITE
  class Transform::Pipeline {
  public:
    typedef Transform Pipelines;

    inline Pipeline(decltype(nullptr)) : _typeless(nullptr) {}
    inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless) : _typeless(kj::mv(typeless)) {}

    inline ::Schema::Vec2F32::Pipeline getPos();

  private:
    ::capnp::AnyPointer::Pipeline _typeless;
    friend class ::capnp::PipelineHook;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::ToDynamic_;
  };
#endif // !CAPNP_LITE

  class Void::Reader {
  public:
    typedef Void Reads;

    Reader() = default;
    inline explicit Reader(::capnp::_::StructReader base) : _reader(base) {}

    inline ::capnp::MessageSize totalSize() const {
      return _reader.totalSize().asPublic();
    }

#if !CAPNP_LITE
    inline ::kj::StringTree toString() const {
      return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
    }
#endif // !CAPNP_LITE

  private:
    ::capnp::_::StructReader _reader;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::ToDynamic_;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::_::PointerHelpers;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::List;
    friend class ::capnp::MessageBuilder;
    friend class ::capnp::Orphanage;
  };

  class Void::Builder {
  public:
    typedef Void Builds;

    Builder() = delete; // Deleted to discourage incorrect usage.
                        // You can explicitly initialize to nullptr instead.
    inline Builder(decltype(nullptr)) {}
    inline explicit Builder(::capnp::_::StructBuilder base) : _builder(base) {}
    inline operator Reader() const {
      return Reader(_builder.asReader());
    }
    inline Reader asReader() const {
      return *this;
    }

    inline ::capnp::MessageSize totalSize() const {
      return asReader().totalSize();
    }
#if !CAPNP_LITE
    inline ::kj::StringTree toString() const {
      return asReader().toString();
    }
#endif // !CAPNP_LITE

  private:
    ::capnp::_::StructBuilder _builder;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::ToDynamic_;
    friend class ::capnp::Orphanage;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::_::PointerHelpers;
  };

#if !CAPNP_LITE
  class Void::Pipeline {
  public:
    typedef Void Pipelines;

    inline Pipeline(decltype(nullptr)) : _typeless(nullptr) {}
    inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless) : _typeless(kj::mv(typeless)) {}

  private:
    ::capnp::AnyPointer::Pipeline _typeless;
    friend class ::capnp::PipelineHook;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::ToDynamic_;
  };
#endif // !CAPNP_LITE

  class Entity::Reader {
  public:
    typedef Entity Reads;

    Reader() = default;
    inline explicit Reader(::capnp::_::StructReader base) : _reader(base) {}

    inline ::capnp::MessageSize totalSize() const {
      return _reader.totalSize().asPublic();
    }

#if !CAPNP_LITE
    inline ::kj::StringTree toString() const {
      return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
    }
#endif // !CAPNP_LITE

    inline ::uint32_t getId() const;

    inline bool hasCompIds() const;
    inline ::capnp::List<::uint16_t, ::capnp::Kind::PRIMITIVE>::Reader getCompIds() const;

    inline bool hasCompData() const;
    inline ::capnp::List<::capnp::Data, ::capnp::Kind::BLOB>::Reader getCompData() const;

  private:
    ::capnp::_::StructReader _reader;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::ToDynamic_;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::_::PointerHelpers;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::List;
    friend class ::capnp::MessageBuilder;
    friend class ::capnp::Orphanage;
  };

  class Entity::Builder {
  public:
    typedef Entity Builds;

    Builder() = delete; // Deleted to discourage incorrect usage.
                        // You can explicitly initialize to nullptr instead.
    inline Builder(decltype(nullptr)) {}
    inline explicit Builder(::capnp::_::StructBuilder base) : _builder(base) {}
    inline operator Reader() const {
      return Reader(_builder.asReader());
    }
    inline Reader asReader() const {
      return *this;
    }

    inline ::capnp::MessageSize totalSize() const {
      return asReader().totalSize();
    }
#if !CAPNP_LITE
    inline ::kj::StringTree toString() const {
      return asReader().toString();
    }
#endif // !CAPNP_LITE

    inline ::uint32_t getId();
    inline void setId(::uint32_t value);

    inline bool hasCompIds();
    inline ::capnp::List<::uint16_t, ::capnp::Kind::PRIMITIVE>::Builder getCompIds();
    inline void setCompIds(::capnp::List<::uint16_t, ::capnp::Kind::PRIMITIVE>::Reader value);
    inline void setCompIds(::kj::ArrayPtr<const ::uint16_t> value);
    inline ::capnp::List<::uint16_t, ::capnp::Kind::PRIMITIVE>::Builder initCompIds(unsigned int size);
    inline void adoptCompIds(::capnp::Orphan<::capnp::List<::uint16_t, ::capnp::Kind::PRIMITIVE>>&& value);
    inline ::capnp::Orphan<::capnp::List<::uint16_t, ::capnp::Kind::PRIMITIVE>> disownCompIds();

    inline bool hasCompData();
    inline ::capnp::List<::capnp::Data, ::capnp::Kind::BLOB>::Builder getCompData();
    inline void setCompData(::capnp::List<::capnp::Data, ::capnp::Kind::BLOB>::Reader value);
    inline void setCompData(::kj::ArrayPtr<const ::capnp::Data::Reader> value);
    inline ::capnp::List<::capnp::Data, ::capnp::Kind::BLOB>::Builder initCompData(unsigned int size);
    inline void adoptCompData(::capnp::Orphan<::capnp::List<::capnp::Data, ::capnp::Kind::BLOB>>&& value);
    inline ::capnp::Orphan<::capnp::List<::capnp::Data, ::capnp::Kind::BLOB>> disownCompData();

  private:
    ::capnp::_::StructBuilder _builder;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::ToDynamic_;
    friend class ::capnp::Orphanage;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::_::PointerHelpers;
  };

#if !CAPNP_LITE
  class Entity::Pipeline {
  public:
    typedef Entity Pipelines;

    inline Pipeline(decltype(nullptr)) : _typeless(nullptr) {}
    inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless) : _typeless(kj::mv(typeless)) {}

  private:
    ::capnp::AnyPointer::Pipeline _typeless;
    friend class ::capnp::PipelineHook;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::ToDynamic_;
  };
#endif // !CAPNP_LITE

  class ComponentIdName::Reader {
  public:
    typedef ComponentIdName Reads;

    Reader() = default;
    inline explicit Reader(::capnp::_::StructReader base) : _reader(base) {}

    inline ::capnp::MessageSize totalSize() const {
      return _reader.totalSize().asPublic();
    }

#if !CAPNP_LITE
    inline ::kj::StringTree toString() const {
      return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
    }
#endif // !CAPNP_LITE

    inline bool hasName() const;
    inline ::capnp::Text::Reader getName() const;

    inline ::uint16_t getCompId() const;

  private:
    ::capnp::_::StructReader _reader;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::ToDynamic_;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::_::PointerHelpers;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::List;
    friend class ::capnp::MessageBuilder;
    friend class ::capnp::Orphanage;
  };

  class ComponentIdName::Builder {
  public:
    typedef ComponentIdName Builds;

    Builder() = delete; // Deleted to discourage incorrect usage.
                        // You can explicitly initialize to nullptr instead.
    inline Builder(decltype(nullptr)) {}
    inline explicit Builder(::capnp::_::StructBuilder base) : _builder(base) {}
    inline operator Reader() const {
      return Reader(_builder.asReader());
    }
    inline Reader asReader() const {
      return *this;
    }

    inline ::capnp::MessageSize totalSize() const {
      return asReader().totalSize();
    }
#if !CAPNP_LITE
    inline ::kj::StringTree toString() const {
      return asReader().toString();
    }
#endif // !CAPNP_LITE

    inline bool hasName();
    inline ::capnp::Text::Builder getName();
    inline void setName(::capnp::Text::Reader value);
    inline ::capnp::Text::Builder initName(unsigned int size);
    inline void adoptName(::capnp::Orphan<::capnp::Text>&& value);
    inline ::capnp::Orphan<::capnp::Text> disownName();

    inline ::uint16_t getCompId();
    inline void setCompId(::uint16_t value);

  private:
    ::capnp::_::StructBuilder _builder;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::ToDynamic_;
    friend class ::capnp::Orphanage;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::_::PointerHelpers;
  };

#if !CAPNP_LITE
  class ComponentIdName::Pipeline {
  public:
    typedef ComponentIdName Pipelines;

    inline Pipeline(decltype(nullptr)) : _typeless(nullptr) {}
    inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless) : _typeless(kj::mv(typeless)) {}

  private:
    ::capnp::AnyPointer::Pipeline _typeless;
    friend class ::capnp::PipelineHook;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::ToDynamic_;
  };
#endif // !CAPNP_LITE

  class State::Reader {
  public:
    typedef State Reads;

    Reader() = default;
    inline explicit Reader(::capnp::_::StructReader base) : _reader(base) {}

    inline ::capnp::MessageSize totalSize() const {
      return _reader.totalSize().asPublic();
    }

#if !CAPNP_LITE
    inline ::kj::StringTree toString() const {
      return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
    }
#endif // !CAPNP_LITE

    inline bool hasRegisteredComponents() const;
    inline ::capnp::List<::Schema::ComponentIdName, ::capnp::Kind::STRUCT>::Reader
    getRegisteredComponents() const;

    inline bool hasEntities() const;
    inline ::capnp::List<::Schema::Entity, ::capnp::Kind::STRUCT>::Reader getEntities() const;

  private:
    ::capnp::_::StructReader _reader;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::ToDynamic_;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::_::PointerHelpers;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::List;
    friend class ::capnp::MessageBuilder;
    friend class ::capnp::Orphanage;
  };

  class State::Builder {
  public:
    typedef State Builds;

    Builder() = delete; // Deleted to discourage incorrect usage.
                        // You can explicitly initialize to nullptr instead.
    inline Builder(decltype(nullptr)) {}
    inline explicit Builder(::capnp::_::StructBuilder base) : _builder(base) {}
    inline operator Reader() const {
      return Reader(_builder.asReader());
    }
    inline Reader asReader() const {
      return *this;
    }

    inline ::capnp::MessageSize totalSize() const {
      return asReader().totalSize();
    }
#if !CAPNP_LITE
    inline ::kj::StringTree toString() const {
      return asReader().toString();
    }
#endif // !CAPNP_LITE

    inline bool hasRegisteredComponents();
    inline ::capnp::List<::Schema::ComponentIdName, ::capnp::Kind::STRUCT>::Builder getRegisteredComponents();
    inline void
    setRegisteredComponents(::capnp::List<::Schema::ComponentIdName, ::capnp::Kind::STRUCT>::Reader value);
    inline ::capnp::List<::Schema::ComponentIdName, ::capnp::Kind::STRUCT>::Builder
    initRegisteredComponents(unsigned int size);
    inline void adoptRegisteredComponents(
        ::capnp::Orphan<::capnp::List<::Schema::ComponentIdName, ::capnp::Kind::STRUCT>>&& value);
    inline ::capnp::Orphan<::capnp::List<::Schema::ComponentIdName, ::capnp::Kind::STRUCT>>
    disownRegisteredComponents();

    inline bool hasEntities();
    inline ::capnp::List<::Schema::Entity, ::capnp::Kind::STRUCT>::Builder getEntities();
    inline void setEntities(::capnp::List<::Schema::Entity, ::capnp::Kind::STRUCT>::Reader value);
    inline ::capnp::List<::Schema::Entity, ::capnp::Kind::STRUCT>::Builder initEntities(unsigned int size);
    inline void
    adoptEntities(::capnp::Orphan<::capnp::List<::Schema::Entity, ::capnp::Kind::STRUCT>>&& value);
    inline ::capnp::Orphan<::capnp::List<::Schema::Entity, ::capnp::Kind::STRUCT>> disownEntities();

  private:
    ::capnp::_::StructBuilder _builder;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::ToDynamic_;
    friend class ::capnp::Orphanage;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::_::PointerHelpers;
  };

#if !CAPNP_LITE
  class State::Pipeline {
  public:
    typedef State Pipelines;

    inline Pipeline(decltype(nullptr)) : _typeless(nullptr) {}
    inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless) : _typeless(kj::mv(typeless)) {}

  private:
    ::capnp::AnyPointer::Pipeline _typeless;
    friend class ::capnp::PipelineHook;
    template <typename, ::capnp::Kind>
    friend struct ::capnp::ToDynamic_;
  };
#endif // !CAPNP_LITE

  // =======================================================================================

  inline float Vec2F32::Reader::getX() const {
    return _reader.getDataField<float>(::capnp::bounded<0>() * ::capnp::ELEMENTS);
  }

  inline float Vec2F32::Builder::getX() {
    return _builder.getDataField<float>(::capnp::bounded<0>() * ::capnp::ELEMENTS);
  }
  inline void Vec2F32::Builder::setX(float value) {
    _builder.setDataField<float>(::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
  }

  inline float Vec2F32::Reader::getY() const {
    return _reader.getDataField<float>(::capnp::bounded<1>() * ::capnp::ELEMENTS);
  }

  inline float Vec2F32::Builder::getY() {
    return _builder.getDataField<float>(::capnp::bounded<1>() * ::capnp::ELEMENTS);
  }
  inline void Vec2F32::Builder::setY(float value) {
    _builder.setDataField<float>(::capnp::bounded<1>() * ::capnp::ELEMENTS, value);
  }

  inline bool Transform::Reader::hasPos() const {
    return !_reader.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
  }
  inline bool Transform::Builder::hasPos() {
    return !_builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
  }
  inline ::Schema::Vec2F32::Reader Transform::Reader::getPos() const {
    return ::capnp::_::PointerHelpers<::Schema::Vec2F32>::get(
        _reader.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS));
  }
  inline ::Schema::Vec2F32::Builder Transform::Builder::getPos() {
    return ::capnp::_::PointerHelpers<::Schema::Vec2F32>::get(
        _builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS));
  }
#if !CAPNP_LITE
  inline ::Schema::Vec2F32::Pipeline Transform::Pipeline::getPos() {
    return ::Schema::Vec2F32::Pipeline(_typeless.getPointerField(0));
  }
#endif // !CAPNP_LITE
  inline void Transform::Builder::setPos(::Schema::Vec2F32::Reader value) {
    ::capnp::_::PointerHelpers<::Schema::Vec2F32>::set(
        _builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS), value);
  }
  inline ::Schema::Vec2F32::Builder Transform::Builder::initPos() {
    return ::capnp::_::PointerHelpers<::Schema::Vec2F32>::init(
        _builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS));
  }
  inline void Transform::Builder::adoptPos(::capnp::Orphan<::Schema::Vec2F32>&& value) {
    ::capnp::_::PointerHelpers<::Schema::Vec2F32>::adopt(
        _builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
  }
  inline ::capnp::Orphan<::Schema::Vec2F32> Transform::Builder::disownPos() {
    return ::capnp::_::PointerHelpers<::Schema::Vec2F32>::disown(
        _builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS));
  }

  inline float Transform::Reader::getRot() const {
    return _reader.getDataField<float>(::capnp::bounded<0>() * ::capnp::ELEMENTS);
  }

  inline float Transform::Builder::getRot() {
    return _builder.getDataField<float>(::capnp::bounded<0>() * ::capnp::ELEMENTS);
  }
  inline void Transform::Builder::setRot(float value) {
    _builder.setDataField<float>(::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
  }

  inline ::uint32_t Entity::Reader::getId() const {
    return _reader.getDataField<::uint32_t>(::capnp::bounded<0>() * ::capnp::ELEMENTS);
  }

  inline ::uint32_t Entity::Builder::getId() {
    return _builder.getDataField<::uint32_t>(::capnp::bounded<0>() * ::capnp::ELEMENTS);
  }
  inline void Entity::Builder::setId(::uint32_t value) {
    _builder.setDataField<::uint32_t>(::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
  }

  inline bool Entity::Reader::hasCompIds() const {
    return !_reader.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
  }
  inline bool Entity::Builder::hasCompIds() {
    return !_builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
  }
  inline ::capnp::List<::uint16_t, ::capnp::Kind::PRIMITIVE>::Reader Entity::Reader::getCompIds() const {
    return ::capnp::_::PointerHelpers<::capnp::List<::uint16_t, ::capnp::Kind::PRIMITIVE>>::get(
        _reader.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS));
  }
  inline ::capnp::List<::uint16_t, ::capnp::Kind::PRIMITIVE>::Builder Entity::Builder::getCompIds() {
    return ::capnp::_::PointerHelpers<::capnp::List<::uint16_t, ::capnp::Kind::PRIMITIVE>>::get(
        _builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS));
  }
  inline void Entity::Builder::setCompIds(::capnp::List<::uint16_t, ::capnp::Kind::PRIMITIVE>::Reader value) {
    ::capnp::_::PointerHelpers<::capnp::List<::uint16_t, ::capnp::Kind::PRIMITIVE>>::set(
        _builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS), value);
  }
  inline void Entity::Builder::setCompIds(::kj::ArrayPtr<const ::uint16_t> value) {
    ::capnp::_::PointerHelpers<::capnp::List<::uint16_t, ::capnp::Kind::PRIMITIVE>>::set(
        _builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS), value);
  }
  inline ::capnp::List<::uint16_t, ::capnp::Kind::PRIMITIVE>::Builder
  Entity::Builder::initCompIds(unsigned int size) {
    return ::capnp::_::PointerHelpers<::capnp::List<::uint16_t, ::capnp::Kind::PRIMITIVE>>::init(
        _builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS), size);
  }
  inline void Entity::Builder::adoptCompIds(
      ::capnp::Orphan<::capnp::List<::uint16_t, ::capnp::Kind::PRIMITIVE>>&& value) {
    ::capnp::_::PointerHelpers<::capnp::List<::uint16_t, ::capnp::Kind::PRIMITIVE>>::adopt(
        _builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
  }
  inline ::capnp::Orphan<::capnp::List<::uint16_t, ::capnp::Kind::PRIMITIVE>>
  Entity::Builder::disownCompIds() {
    return ::capnp::_::PointerHelpers<::capnp::List<::uint16_t, ::capnp::Kind::PRIMITIVE>>::disown(
        _builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS));
  }

  inline bool Entity::Reader::hasCompData() const {
    return !_reader.getPointerField(::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
  }
  inline bool Entity::Builder::hasCompData() {
    return !_builder.getPointerField(::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
  }
  inline ::capnp::List<::capnp::Data, ::capnp::Kind::BLOB>::Reader Entity::Reader::getCompData() const {
    return ::capnp::_::PointerHelpers<::capnp::List<::capnp::Data, ::capnp::Kind::BLOB>>::get(
        _reader.getPointerField(::capnp::bounded<1>() * ::capnp::POINTERS));
  }
  inline ::capnp::List<::capnp::Data, ::capnp::Kind::BLOB>::Builder Entity::Builder::getCompData() {
    return ::capnp::_::PointerHelpers<::capnp::List<::capnp::Data, ::capnp::Kind::BLOB>>::get(
        _builder.getPointerField(::capnp::bounded<1>() * ::capnp::POINTERS));
  }
  inline void Entity::Builder::setCompData(::capnp::List<::capnp::Data, ::capnp::Kind::BLOB>::Reader value) {
    ::capnp::_::PointerHelpers<::capnp::List<::capnp::Data, ::capnp::Kind::BLOB>>::set(
        _builder.getPointerField(::capnp::bounded<1>() * ::capnp::POINTERS), value);
  }
  inline void Entity::Builder::setCompData(::kj::ArrayPtr<const ::capnp::Data::Reader> value) {
    ::capnp::_::PointerHelpers<::capnp::List<::capnp::Data, ::capnp::Kind::BLOB>>::set(
        _builder.getPointerField(::capnp::bounded<1>() * ::capnp::POINTERS), value);
  }
  inline ::capnp::List<::capnp::Data, ::capnp::Kind::BLOB>::Builder
  Entity::Builder::initCompData(unsigned int size) {
    return ::capnp::_::PointerHelpers<::capnp::List<::capnp::Data, ::capnp::Kind::BLOB>>::init(
        _builder.getPointerField(::capnp::bounded<1>() * ::capnp::POINTERS), size);
  }
  inline void
  Entity::Builder::adoptCompData(::capnp::Orphan<::capnp::List<::capnp::Data, ::capnp::Kind::BLOB>>&& value) {
    ::capnp::_::PointerHelpers<::capnp::List<::capnp::Data, ::capnp::Kind::BLOB>>::adopt(
        _builder.getPointerField(::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
  }
  inline ::capnp::Orphan<::capnp::List<::capnp::Data, ::capnp::Kind::BLOB>>
  Entity::Builder::disownCompData() {
    return ::capnp::_::PointerHelpers<::capnp::List<::capnp::Data, ::capnp::Kind::BLOB>>::disown(
        _builder.getPointerField(::capnp::bounded<1>() * ::capnp::POINTERS));
  }

  inline bool ComponentIdName::Reader::hasName() const {
    return !_reader.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
  }
  inline bool ComponentIdName::Builder::hasName() {
    return !_builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
  }
  inline ::capnp::Text::Reader ComponentIdName::Reader::getName() const {
    return ::capnp::_::PointerHelpers<::capnp::Text>::get(
        _reader.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS));
  }
  inline ::capnp::Text::Builder ComponentIdName::Builder::getName() {
    return ::capnp::_::PointerHelpers<::capnp::Text>::get(
        _builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS));
  }
  inline void ComponentIdName::Builder::setName(::capnp::Text::Reader value) {
    ::capnp::_::PointerHelpers<::capnp::Text>::set(
        _builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS), value);
  }
  inline ::capnp::Text::Builder ComponentIdName::Builder::initName(unsigned int size) {
    return ::capnp::_::PointerHelpers<::capnp::Text>::init(
        _builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS), size);
  }
  inline void ComponentIdName::Builder::adoptName(::capnp::Orphan<::capnp::Text>&& value) {
    ::capnp::_::PointerHelpers<::capnp::Text>::adopt(
        _builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
  }
  inline ::capnp::Orphan<::capnp::Text> ComponentIdName::Builder::disownName() {
    return ::capnp::_::PointerHelpers<::capnp::Text>::disown(
        _builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS));
  }

  inline ::uint16_t ComponentIdName::Reader::getCompId() const {
    return _reader.getDataField<::uint16_t>(::capnp::bounded<0>() * ::capnp::ELEMENTS);
  }

  inline ::uint16_t ComponentIdName::Builder::getCompId() {
    return _builder.getDataField<::uint16_t>(::capnp::bounded<0>() * ::capnp::ELEMENTS);
  }
  inline void ComponentIdName::Builder::setCompId(::uint16_t value) {
    _builder.setDataField<::uint16_t>(::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
  }

  inline bool State::Reader::hasRegisteredComponents() const {
    return !_reader.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
  }
  inline bool State::Builder::hasRegisteredComponents() {
    return !_builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
  }
  inline ::capnp::List<::Schema::ComponentIdName, ::capnp::Kind::STRUCT>::Reader
  State::Reader::getRegisteredComponents() const {
    return ::capnp::_::PointerHelpers<::capnp::List<::Schema::ComponentIdName, ::capnp::Kind::STRUCT>>::get(
        _reader.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS));
  }
  inline ::capnp::List<::Schema::ComponentIdName, ::capnp::Kind::STRUCT>::Builder
  State::Builder::getRegisteredComponents() {
    return ::capnp::_::PointerHelpers<::capnp::List<::Schema::ComponentIdName, ::capnp::Kind::STRUCT>>::get(
        _builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS));
  }
  inline void State::Builder::setRegisteredComponents(
      ::capnp::List<::Schema::ComponentIdName, ::capnp::Kind::STRUCT>::Reader value) {
    ::capnp::_::PointerHelpers<::capnp::List<::Schema::ComponentIdName, ::capnp::Kind::STRUCT>>::set(
        _builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS), value);
  }
  inline ::capnp::List<::Schema::ComponentIdName, ::capnp::Kind::STRUCT>::Builder
  State::Builder::initRegisteredComponents(unsigned int size) {
    return ::capnp::_::PointerHelpers<::capnp::List<::Schema::ComponentIdName, ::capnp::Kind::STRUCT>>::init(
        _builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS), size);
  }
  inline void State::Builder::adoptRegisteredComponents(
      ::capnp::Orphan<::capnp::List<::Schema::ComponentIdName, ::capnp::Kind::STRUCT>>&& value) {
    ::capnp::_::PointerHelpers<::capnp::List<::Schema::ComponentIdName, ::capnp::Kind::STRUCT>>::adopt(
        _builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
  }
  inline ::capnp::Orphan<::capnp::List<::Schema::ComponentIdName, ::capnp::Kind::STRUCT>>
  State::Builder::disownRegisteredComponents() {
    return ::capnp::_::PointerHelpers<::capnp::List<::Schema::ComponentIdName, ::capnp::Kind::STRUCT>>::
        disown(_builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS));
  }

  inline bool State::Reader::hasEntities() const {
    return !_reader.getPointerField(::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
  }
  inline bool State::Builder::hasEntities() {
    return !_builder.getPointerField(::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
  }
  inline ::capnp::List<::Schema::Entity, ::capnp::Kind::STRUCT>::Reader State::Reader::getEntities() const {
    return ::capnp::_::PointerHelpers<::capnp::List<::Schema::Entity, ::capnp::Kind::STRUCT>>::get(
        _reader.getPointerField(::capnp::bounded<1>() * ::capnp::POINTERS));
  }
  inline ::capnp::List<::Schema::Entity, ::capnp::Kind::STRUCT>::Builder State::Builder::getEntities() {
    return ::capnp::_::PointerHelpers<::capnp::List<::Schema::Entity, ::capnp::Kind::STRUCT>>::get(
        _builder.getPointerField(::capnp::bounded<1>() * ::capnp::POINTERS));
  }
  inline void
  State::Builder::setEntities(::capnp::List<::Schema::Entity, ::capnp::Kind::STRUCT>::Reader value) {
    ::capnp::_::PointerHelpers<::capnp::List<::Schema::Entity, ::capnp::Kind::STRUCT>>::set(
        _builder.getPointerField(::capnp::bounded<1>() * ::capnp::POINTERS), value);
  }
  inline ::capnp::List<::Schema::Entity, ::capnp::Kind::STRUCT>::Builder
  State::Builder::initEntities(unsigned int size) {
    return ::capnp::_::PointerHelpers<::capnp::List<::Schema::Entity, ::capnp::Kind::STRUCT>>::init(
        _builder.getPointerField(::capnp::bounded<1>() * ::capnp::POINTERS), size);
  }
  inline void State::Builder::adoptEntities(
      ::capnp::Orphan<::capnp::List<::Schema::Entity, ::capnp::Kind::STRUCT>>&& value) {
    ::capnp::_::PointerHelpers<::capnp::List<::Schema::Entity, ::capnp::Kind::STRUCT>>::adopt(
        _builder.getPointerField(::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
  }
  inline ::capnp::Orphan<::capnp::List<::Schema::Entity, ::capnp::Kind::STRUCT>>
  State::Builder::disownEntities() {
    return ::capnp::_::PointerHelpers<::capnp::List<::Schema::Entity, ::capnp::Kind::STRUCT>>::disown(
        _builder.getPointerField(::capnp::bounded<1>() * ::capnp::POINTERS));
  }

} // namespace Schema

CAPNP_END_HEADER
